
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."auto_shop_inventory" (
    "id" bigint NOT NULL,
    "auto_shop_id" bigint NOT NULL,
    "car_part_id" bigint,
    "quantity" bigint
);

ALTER TABLE "public"."auto_shop_inventory" OWNER TO "postgres";

ALTER TABLE "public"."auto_shop_inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auto_shop_inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."auto_shops" (
    "id" bigint NOT NULL,
    "name" "text",
    "address" "text" DEFAULT ''::"text"
);

ALTER TABLE "public"."auto_shops" OWNER TO "postgres";

ALTER TABLE "public"."auto_shops" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auto_shops_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."car_parts" (
    "id" bigint NOT NULL,
    "name" "text"
);

ALTER TABLE "public"."car_parts" OWNER TO "postgres";

ALTER TABLE "public"."car_parts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."car_parts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."auto_shop_inventory"
    ADD CONSTRAINT "auto_shop_inventory_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."auto_shops"
    ADD CONSTRAINT "auto_shops_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."car_parts"
    ADD CONSTRAINT "car_parts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."auto_shop_inventory"
    ADD CONSTRAINT "public_auto_shop_inventory_auto_shop_id_fkey" FOREIGN KEY ("auto_shop_id") REFERENCES "public"."auto_shops"("id");

ALTER TABLE ONLY "public"."auto_shop_inventory"
    ADD CONSTRAINT "public_auto_shop_inventory_car_part_id_fkey" FOREIGN KEY ("car_part_id") REFERENCES "public"."car_parts"("id");

ALTER TABLE "public"."auto_shop_inventory" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."auto_shops" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."car_parts" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."auto_shop_inventory" TO "anon";
GRANT ALL ON TABLE "public"."auto_shop_inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."auto_shop_inventory" TO "service_role";

GRANT ALL ON SEQUENCE "public"."auto_shop_inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auto_shop_inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auto_shop_inventory_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."auto_shops" TO "anon";
GRANT ALL ON TABLE "public"."auto_shops" TO "authenticated";
GRANT ALL ON TABLE "public"."auto_shops" TO "service_role";

GRANT ALL ON SEQUENCE "public"."auto_shops_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auto_shops_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auto_shops_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."car_parts" TO "anon";
GRANT ALL ON TABLE "public"."car_parts" TO "authenticated";
GRANT ALL ON TABLE "public"."car_parts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."car_parts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."car_parts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."car_parts_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
